import fs from 'fs';

// Group A: Pages 1 to 10 (ESTADO, EMPRESA, LEGAJO)
const groupA_raw = `
ACTIVO Talleres Metalúrgicos Crucianelli 2122
INACTIVO Talleres Metalúrgicos Crucianelli 449
ACTIVO Talleres Metalúrgicos Crucianelli 405
ACTIVO Talleres Metalúrgicos Crucianelli 136
INACTIVO Talleres Metalúrgicos Crucianelli 18
INACTIVO Talleres Metalúrgicos Crucianelli 596
ACTIVO Talleres Metalúrgicos Crucianelli 329
ACTIVO Talleres Metalúrgicos Crucianelli 597
ACTIVO Talleres Metalúrgicos Crucianelli 411
ACTIVO Talleres Metalúrgicos Crucianelli 122
ACTIVO Talleres Metalúrgicos Crucianelli 580
ACTIVO Talleres Metalúrgicos Crucianelli 358
INACTIVO Talleres Metalúrgicos Crucianelli 275
ACTIVO Talleres Metalúrgicos Crucianelli 437
ACTIVO Talleres Metalúrgicos Crucianelli 459
ACTIVO Talleres Metalúrgicos Crucianelli 435
INACTIVO Talleres Metalúrgicos Crucianelli 434
ACTIVO Talleres Metalúrgicos Crucianelli 450
ACTIVO Talleres Metalúrgicos Crucianelli 387
ACTIVO Talleres Metalúrgicos Crucianelli 495
ACTIVO Talleres Metalúrgicos Crucianelli 97
ACTIVO Talleres Metalúrgicos Crucianelli 200
INACTIVO Talleres Metalúrgicos Crucianelli 2119
ACTIVO Talleres Metalúrgicos Crucianelli 285
ACTIVO Talleres Metalúrgicos Crucianelli 54
ACTIVO Talleres Metalúrgicos Crucianelli 237
ACTIVO Talleres Metalúrgicos Crucianelli 538
INACTIVO Talleres Metalúrgicos Crucianelli 313
INACTIVO Talleres Metalúrgicos Crucianelli 326
ACTIVO Talleres Metalúrgicos Crucianelli 393
ACTIVO Talleres Metalúrgicos Crucianelli 431
ACTIVO Talleres Metalúrgicos Crucianelli 26
ACTIVO Talleres Metalúrgicos Crucianelli 66
ACTIVO Talleres Metalúrgicos Crucianelli 451
ACTIVO Talleres Metalúrgicos Crucianelli 2123
INACTIVO Talleres Metalúrgicos Crucianelli 592
ACTIVO Talleres Metalúrgicos Crucianelli 496
ACTIVO Talleres Metalúrgicos Crucianelli 549
ACTIVO Talleres Metalúrgicos Crucianelli 171
ACTIVO Talleres Metalúrgicos Crucianelli 225
ACTIVO Talleres Metalúrgicos Crucianelli 362
ACTIVO Talleres Metalúrgicos Crucianelli 247
ACTIVO Talleres Metalúrgicos Crucianelli 575
ACTIVO Talleres Metalúrgicos Crucianelli 562
ACTIVO Talleres Metalúrgicos Crucianelli 442
ACTIVO Talleres Metalúrgicos Crucianelli 366
ACTIVO Talleres Metalúrgicos Crucianelli 357
ACTIVO Talleres Metalúrgicos Crucianelli 332
ACTIVO Talleres Metalúrgicos Crucianelli 47
ACTIVO Talleres Metalúrgicos Crucianelli 51
INACTIVO Talleres Metalúrgicos Crucianelli 2134
INACTIVO Talleres Metalúrgicos Crucianelli 351
INACTIVO Talleres Metalúrgicos Crucianelli 215
INACTIVO Talleres Metalúrgicos Crucianelli 2109
ACTIVO Talleres Metalúrgicos Crucianelli 2110
ACTIVO Talleres Metalúrgicos Crucianelli 306
ACTIVO Talleres Metalúrgicos Crucianelli 2132
ACTIVO Talleres Metalúrgicos Crucianelli 539
ACTIVO Talleres Metalúrgicos Crucianelli 2128
ACTIVO Talleres Metalúrgicos Crucianelli 576
ACTIVO Talleres Metalúrgicos Crucianelli 468
INACTIVO Talleres Metalúrgicos Crucianelli 523
ACTIVO Talleres Metalúrgicos Crucianelli 153
ACTIVO Talleres Metalúrgicos Crucianelli 520
INACTIVO Talleres Metalúrgicos Crucianelli 543
ACTIVO Talleres Metalúrgicos Crucianelli 245
ACTIVO Talleres Metalúrgicos Crucianelli 38
INACTIVO Talleres Metalúrgicos Crucianelli 2131
ACTIVO Talleres Metalúrgicos Crucianelli 152
ACTIVO Talleres Metalúrgicos Crucianelli 524
ACTIVO Talleres Metalúrgicos Crucianelli 268
ACTIVO Talleres Metalúrgicos Crucianelli 295
ACTIVO Talleres Metalúrgicos Crucianelli 333
INACTIVO Talleres Metalúrgicos Crucianelli 48
ACTIVO Talleres Metalúrgicos Crucianelli 452
ACTIVO Talleres Metalúrgicos Crucianelli 77
ACTIVO Talleres Metalúrgicos Crucianelli 165
ACTIVO Talleres Metalúrgicos Crucianelli 392
INACTIVO Talleres Metalúrgicos Crucianelli 492
INACTIVO Talleres Metalúrgicos Crucianelli 369
INACTIVO Talleres Metalúrgicos Crucianelli 513
ACTIVO Talleres Metalúrgicos Crucianelli 346
ACTIVO Talleres Metalúrgicos Crucianelli 80
INACTIVO Talleres Metalúrgicos Crucianelli 293
ACTIVO Talleres Metalúrgicos Crucianelli 321
ACTIVO Talleres Metalúrgicos Crucianelli 78
ACTIVO Talleres Metalúrgicos Crucianelli 438
ACTIVO Talleres Metalúrgicos Crucianelli 498
ACTIVO Talleres Metalúrgicos Crucianelli 103
ACTIVO Talleres Metalúrgicos Crucianelli 488
ACTIVO Talleres Metalúrgicos Crucianelli 2112
ACTIVO Talleres Metalúrgicos Crucianelli 96
ACTIVO Talleres Metalúrgicos Crucianelli 59
ACTIVO Talleres Metalúrgicos Crucianelli 383
ACTIVO Talleres Metalúrgicos Crucianelli 90
ACTIVO Talleres Metalúrgicos Crucianelli 493
ACTIVO Talleres Metalúrgicos Crucianelli 568
ACTIVO Talleres Metalúrgicos Crucianelli 384
ACTIVO Talleres Metalúrgicos Crucianelli 318
ACTIVO Talleres Metalúrgicos Crucianelli 2113
INACTIVO Talleres Metalúrgicos Crucianelli 541
ACTIVO Talleres Metalúrgicos Crucianelli 423
INACTIVO Talleres Metalúrgicos Crucianelli 2124
INACTIVO Talleres Metalúrgicos Crucianelli 490
INACTIVO Talleres Metalúrgicos Crucianelli 560
ACTIVO Talleres Metalúrgicos Crucianelli 158
ACTIVO Talleres Metalúrgicos Crucianelli 2102
ACTIVO Talleres Metalúrgicos Crucianelli 74
INACTIVO Talleres Metalúrgicos Crucianelli 607
ACTIVO Talleres Metalúrgicos Crucianelli 52
ACTIVO Talleres Metalúrgicos Crucianelli 220
INACTIVO Talleres Metalúrgicos Crucianelli 2105
ACTIVO Talleres Metalúrgicos Crucianelli 85
ACTIVO Talleres Metalúrgicos Crucianelli 314
ACTIVO Talleres Metalúrgicos Crucianelli 515
30/04/2026 INACTIVO Talleres Metalúrgicos Crucianelli 564
ACTIVO Talleres Metalúrgicos Crucianelli 301
ACTIVO Talleres Metalúrgicos Crucianelli 571
ACTIVO Talleres Metalúrgicos Crucianelli 600
ACTIVO Talleres Metalúrgicos Crucianelli 300
ACTIVO Talleres Metalúrgicos Crucianelli 17
ACTIVO Talleres Metalúrgicos Crucianelli 304
ACTIVO Talleres Metalúrgicos Crucianelli 23
ACTIVO Talleres Metalúrgicos Crucianelli 24
ACTIVO Talleres Metalúrgicos Crucianelli 9
ACTIVO Talleres Metalúrgicos Crucianelli 206
INACTIVO Talleres Metalúrgicos Crucianelli 569
ACTIVO Talleres Metalúrgicos Crucianelli 503
INACTIVO Talleres Metalúrgicos Crucianelli 353
ACTIVO Talleres Metalúrgicos Crucianelli 536
ACTIVO Talleres Metalúrgicos Crucianelli 105
ACTIVO Talleres Metalúrgicos Crucianelli 107
ACTIVO Talleres Metalúrgicos Crucianelli 28
ACTIVO Talleres Metalúrgicos Crucianelli 230
ACTIVO Talleres Metalúrgicos Crucianelli 456
ACTIVO Talleres Metalúrgicos Crucianelli 586
ACTIVO Talleres Metalúrgicos Crucianelli 519
ACTIVO Talleres Metalúrgicos Crucianelli 427
ACTIVO Talleres Metalúrgicos Crucianelli 527
ACTIVO Talleres Metalúrgicos Crucianelli 229
ACTIVO Talleres Metalúrgicos Crucianelli 319
ACTIVO Talleres Metalúrgicos Crucianelli 462
ACTIVO Talleres Metalúrgicos Crucianelli 428
ACTIVO Talleres Metalúrgicos Crucianelli 2135
INACTIVO Talleres Metalúrgicos Crucianelli 480
INACTIVO Talleres Metalúrgicos Crucianelli 484
ACTIVO Talleres Metalúrgicos Crucianelli 418
INACTIVO Talleres Metalúrgicos Crucianelli 265
ACTIVO Talleres Metalúrgicos Crucianelli 117
ACTIVO Talleres Metalúrgicos Crucianelli 320
ACTIVO Talleres Metalúrgicos Crucianelli 172
ACTIVO Talleres Metalúrgicos Crucianelli 390
ACTIVO Talleres Metalúrgicos Crucianelli 445
ACTIVO Talleres Metalúrgicos Crucianelli 553
24/04/2026 INACTIVO Talleres Metalúrgicos Crucianelli 540
ACTIVO Talleres Metalúrgicos Crucianelli 86
INACTIVO Talleres Metalúrgicos Crucianelli 2103
ACTIVO Talleres Metalúrgicos Crucianelli 307
ACTIVO Talleres Metalúrgicos Crucianelli 94
ACTIVO Talleres Metalúrgicos Crucianelli 65
ACTIVO Talleres Metalúrgicos Crucianelli 264
ACTIVO Talleres Metalúrgicos Crucianelli 2136
ACTIVO Talleres Metalúrgicos Crucianelli 440
INACTIVO Talleres Metalúrgicos Crucianelli 365
INACTIVO Talleres Metalúrgicos Crucianelli 599
ACTIVO Talleres Metalúrgicos Crucianelli 278
ACTIVO Talleres Metalúrgicos Crucianelli 2126
ACTIVO Talleres Metalúrgicos Crucianelli 530
ACTIVO Talleres Metalúrgicos Crucianelli 315
ACTIVO Talleres Metalúrgicos Crucianelli 2133
INACTIVO Talleres Metalúrgicos Crucianelli 355
INACTIVO Talleres Metalúrgicos Crucianelli 325
ACTIVO Talleres Metalúrgicos Crucianelli 453
INACTIVO Talleres Metalúrgicos Crucianelli 2114
ACTIVO Talleres Metalúrgicos Crucianelli 197
ACTIVO Talleres Metalúrgicos Crucianelli 531
ACTIVO Talleres Metalúrgicos Crucianelli 446
ACTIVO Talleres Metalúrgicos Crucianelli 81
ACTIVO Talleres Metalúrgicos Crucianelli 394
ACTIVO Talleres Metalúrgicos Crucianelli 454
ACTIVO Talleres Metalúrgicos Crucianelli 309
ACTIVO Talleres Metalúrgicos Crucianelli 502
ACTIVO Talleres Metalúrgicos Crucianelli 273
ACTIVO Talleres Metalúrgicos Crucianelli 53
ACTIVO Talleres Metalúrgicos Crucianelli 557
ACTIVO Talleres Metalúrgicos Crucianelli 581
ACTIVO Talleres Metalúrgicos Crucianelli 443
ACTIVO Talleres Metalúrgicos Crucianelli 391
ACTIVO Talleres Metalúrgicos Crucianelli 260
ACTIVO Talleres Metalúrgicos Crucianelli 590
ACTIVO Talleres Metalúrgicos Crucianelli 49
ACTIVO Talleres Metalúrgicos Crucianelli 603
ACTIVO Talleres Metalúrgicos Crucianelli 71
ACTIVO Talleres Metalúrgicos Crucianelli 201
ACTIVO Talleres Metalúrgicos Crucianelli 297
ACTIVO Talleres Metalúrgicos Crucianelli 169
ACTIVO Talleres Metalúrgicos Crucianelli 83
ACTIVO Talleres Metalúrgicos Crucianelli 236
ACTIVO Talleres Metalúrgicos Crucianelli 330
ACTIVO Talleres Metalúrgicos Crucianelli 591
ACTIVO Talleres Metalúrgicos Crucianelli 516
INACTIVO Talleres Metalúrgicos Crucianelli 464
ACTIVO Talleres Metalúrgicos Crucianelli 606
INACTIVO Talleres Metalúrgicos Crucianelli 584
ACTIVO Talleres Metalúrgicos Crucianelli 535
ACTIVO Talleres Metalúrgicos Crucianelli 262
ACTIVO Talleres Metalúrgicos Crucianelli 267
ACTIVO Talleres Metalúrgicos Crucianelli 561
ACTIVO Talleres Metalúrgicos Crucianelli 563
ACTIVO Talleres Metalúrgicos Crucianelli 537
ACTIVO Talleres Metalúrgicos Crucianelli 559
ACTIVO Talleres Metalúrgicos Crucianelli 286
INACTIVO Talleres Metalúrgicos Crucianelli 303
ACTIVO Talleres Metalúrgicos Crucianelli 433
INACTIVO Talleres Metalúrgicos Crucianelli 441
ACTIVO Talleres Metalúrgicos Crucianelli 457
ACTIVO Talleres Metalúrgicos Crucianelli 554
ACTIVO Talleres Metalúrgicos Crucianelli 514
ACTIVO Talleres Metalúrgicos Crucianelli 533
ACTIVO Talleres Metalúrgicos Crucianelli 352
ACTIVO Talleres Metalúrgicos Crucianelli 252
ACTIVO Talleres Metalúrgicos Crucianelli 602
ACTIVO Talleres Metalúrgicos Crucianelli 555
ACTIVO Talleres Metalúrgicos Crucianelli 370
ACTIVO Talleres Metalúrgicos Crucianelli 565
INACTIVO Talleres Metalúrgicos Crucianelli 542
ACTIVO Talleres Metalúrgicos Crucianelli 556
ACTIVO Talleres Metalúrgicos Crucianelli 341
ACTIVO Talleres Metalúrgicos Crucianelli 589
ACTIVO Talleres Metalúrgicos Crucianelli 2117
ACTIVO Talleres Metalúrgicos Crucianelli 2130
ACTIVO Talleres Metalúrgicos Crucianelli 345
ACTIVO Talleres Metalúrgicos Crucianelli 425
ACTIVO Talleres Metalúrgicos Crucianelli 72
ACTIVO Talleres Metalúrgicos Crucianelli 532
ACTIVO Talleres Metalúrgicos Crucianelli 160
INACTIVO Talleres Metalúrgicos Crucianelli 2115
ACTIVO Talleres Metalúrgicos Crucianelli 170
INACTIVO Talleres Metalúrgicos Crucianelli 588
ACTIVO Talleres Metalúrgicos Crucianelli 359
ACTIVO Talleres Metalúrgicos Crucianelli 164
ACTIVO Talleres Metalúrgicos Crucianelli 334
ACTIVO Talleres Metalúrgicos Crucianelli 305
ACTIVO Talleres Metalúrgicos Crucianelli 573
ACTIVO Talleres Metalúrgicos Crucianelli 545
INACTIVO Talleres Metalúrgicos Crucianelli 280
ACTIVO Talleres Metalúrgicos Crucianelli 299
INACTIVO Talleres Metalúrgicos Crucianelli 595
ACTIVO Talleres Metalúrgicos Crucianelli 421
INACTIVO Talleres Metalúrgicos Crucianelli 585
INACTIVO Talleres Metalúrgicos Crucianelli 482
ACTIVO Talleres Metalúrgicos Crucianelli 259
ACTIVO Talleres Metalúrgicos Crucianelli 250
ACTIVO Talleres Metalúrgicos Crucianelli 525
ACTIVO Talleres Metalúrgicos Crucianelli 100
ACTIVO Talleres Metalúrgicos Crucianelli 578
ACTIVO Talleres Metalúrgicos Crucianelli 458
INACTIVO Talleres Metalúrgicos Crucianelli 598
ACTIVO Talleres Metalúrgicos Crucianelli 328
INACTIVO Talleres Metalúrgicos Crucianelli 2125
INACTIVO Talleres Metalúrgicos Crucianelli 579
ACTIVO Talleres Metalúrgicos Crucianelli 447
ACTIVO Talleres Metalúrgicos Crucianelli 253
INACTIVO Talleres Metalúrgicos Crucianelli 551
INACTIVO Talleres Metalúrgicos Crucianelli 402
ACTIVO Talleres Metalúrgicos Crucianelli 611
INACTIVO Talleres Metalúrgicos Crucianelli 570
ACTIVO Talleres Metalúrgicos Crucianelli 302
ACTIVO Talleres Metalúrgicos Crucianelli 605
ACTIVO Talleres Metalúrgicos Crucianelli 550
ACTIVO Talleres Metalúrgicos Crucianelli 135
ACTIVO Talleres Metalúrgicos Crucianelli 22
ACTIVO Talleres Metalúrgicos Crucianelli 70
ACTIVO Talleres Metalúrgicos Crucianelli 566
ACTIVO Talleres Metalúrgicos Crucianelli 311
INACTIVO Talleres Metalúrgicos Crucianelli 609
ACTIVO Talleres Metalúrgicos Crucianelli 612
ACTIVO Talleres Metalúrgicos Crucianelli 400
INACTIVO Talleres Metalúrgicos Crucianelli 209
ACTIVO Talleres Metalúrgicos Crucianelli 572
ACTIVO Talleres Metalúrgicos Crucianelli 582
INACTIVO Talleres Metalúrgicos Crucianelli 526
ACTIVO Talleres Metalúrgicos Crucianelli 412
ACTIVO Talleres Metalúrgicos Crucianelli 42
ACTIVO Talleres Metalúrgicos Crucianelli 2104
ACTIVO Talleres Metalúrgicos Crucianelli 64
ACTIVO Talleres Metalúrgicos Crucianelli 587
ACTIVO Talleres Metalúrgicos Crucianelli 239
ACTIVO Talleres Metalúrgicos Crucianelli 2121
ACTIVO Talleres Metalúrgicos Crucianelli 2116
ACTIVO Talleres Metalúrgicos Crucianelli 251
INACTIVO Talleres Metalúrgicos Crucianelli 470
INACTIVO Talleres Metalúrgicos Crucianelli 92
INACTIVO Talleres Metalúrgicos Crucianelli 534
ACTIVO Talleres Metalúrgicos Crucianelli 296
ACTIVO Talleres Metalúrgicos Crucianelli 322
INACTIVO Talleres Metalúrgicos Crucianelli 593
ACTIVO Talleres Metalúrgicos Crucianelli 240
ACTIVO Talleres Metalúrgicos Crucianelli 2101
ACTIVO Talleres Metalúrgicos Crucianelli 99
ACTIVO Talleres Metalúrgicos Crucianelli 574
ACTIVO Talleres Metalúrgicos Crucianelli 436
ACTIVO Talleres Metalúrgicos Crucianelli 478
ACTIVO Talleres Metalúrgicos Crucianelli 399
INACTIVO Talleres Metalúrgicos Crucianelli 506
ACTIVO Talleres Metalúrgicos Crucianelli 410
INACTIVO Talleres Metalúrgicos Crucianelli 396
INACTIVO Talleres Metalúrgicos Crucianelli 577
ACTIVO Talleres Metalúrgicos Crucianelli 558
INACTIVO Talleres Metalúrgicos Crucianelli 604
ACTIVO Talleres Metalúrgicos Crucianelli 175
INACTIVO Talleres Metalúrgicos Crucianelli 528
INACTIVO Talleres Metalúrgicos Crucianelli 552
ACTIVO Talleres Metalúrgicos Crucianelli 408
ACTIVO Talleres Metalúrgicos Crucianelli 183
ACTIVO Talleres Metalúrgicos Crucianelli 2127
ACTIVO Talleres Metalúrgicos Crucianelli 397
ACTIVO Talleres Metalúrgicos Crucianelli 31
ACTIVO Talleres Metalúrgicos Crucianelli 406
ACTIVO Talleres Metalúrgicos Crucianelli 424
ACTIVO Talleres Metalúrgicos Crucianelli 342
ACTIVO Talleres Metalúrgicos Crucianelli 289
ACTIVO Talleres Metalúrgicos Crucianelli 337
ACTIVO Talleres Metalúrgicos Crucianelli 608
ACTIVO Talleres Metalúrgicos Crucianelli 323
ACTIVO Talleres Metalúrgicos Crucianelli 547
ACTIVO Talleres Metalúrgicos Crucianelli 382
ACTIVO Talleres Metalúrgicos Crucianelli 601
ACTIVO Talleres Metalúrgicos Crucianelli 500
ACTIVO Talleres Metalúrgicos Crucianelli 68
ACTIVO Talleres Metalúrgicos Crucianelli 25
ACTIVO Talleres Metalúrgicos Crucianelli 226
ACTIVO Talleres Metalúrgicos Crucianelli 2120
ACTIVO Talleres Metalúrgicos Crucianelli 511
ACTIVO Talleres Metalúrgicos Crucianelli 430
ACTIVO Talleres Metalúrgicos Crucianelli 243
ACTIVO Talleres Metalúrgicos Crucianelli 2111
ACTIVO Talleres Metalúrgicos Crucianelli 374
ACTIVO Talleres Metalúrgicos Crucianelli 487
ACTIVO Talleres Metalúrgicos Crucianelli 2118
ACTIVO Talleres Metalúrgicos Crucianelli 494
ACTIVO Talleres Metalúrgicos Crucianelli 385
ACTIVO Talleres Metalúrgicos Crucianelli 475
ACTIVO Talleres Metalúrgicos Crucianelli 35
ACTIVO Talleres Metalúrgicos Crucianelli 2129
ACTIVO Talleres Metalúrgicos Crucianelli 510
ACTIVO Talleres Metalúrgicos Crucianelli 386
ACTIVO Talleres Metalúrgicos Crucianelli 5
ACTIVO Talleres Metalúrgicos Crucianelli 101
INACTIVO Talleres Metalúrgicos Crucianelli 474
INACTIVO Talleres Metalúrgicos Crucianelli 376
ACTIVO Talleres Metalúrgicos Crucianelli 377
ACTIVO Talleres Metalúrgicos Crucianelli 594
ACTIVO Talleres Metalúrgicos Crucianelli 327
INACTIVO Talleres Metalúrgicos Crucianelli 509
INACTIVO Talleres Metalúrgicos Crucianelli 364
INACTIVO Talleres Metalúrgicos Crucianelli 473
ACTIVO Talleres Metalúrgicos Crucianelli 119
ACTIVO Talleres Metalúrgicos Crucianelli 210
ACTIVO Talleres Metalúrgicos Crucianelli 367
ACTIVO Talleres Metalúrgicos Crucianelli 294
ACTIVO Talleres Metalúrgicos Crucianelli 56
ACTIVO Talleres Metalúrgicos Crucianelli 2108
ACTIVO Talleres Metalúrgicos Crucianelli 277
ACTIVO Talleres Metalúrgicos Crucianelli 46
ACTIVO Talleres Metalúrgicos Crucianelli 30
ACTIVO Talleres Metalúrgicos Crucianelli 486
ACTIVO Talleres Metalúrgicos Crucianelli 461
ACTIVO Talleres Metalúrgicos Crucianelli 10
ACTIVO Talleres Metalúrgicos Crucianelli 139
ACTIVO Talleres Metalúrgicos Crucianelli 2107
ACTIVO Talleres Metalúrgicos Crucianelli 290
ACTIVO Talleres Metalúrgicos Crucianelli 67
ACTIVO Talleres Metalúrgicos Crucianelli 288
ACTIVO Talleres Metalúrgicos Crucianelli 203
ACTIVO Talleres Metalúrgicos Crucianelli 522
INACTIVO Talleres Metalúrgicos Crucianelli 529
ACTIVO Talleres Metalúrgicos Crucianelli 455
ACTIVO Talleres Metalúrgicos Crucianelli 276
ACTIVO Talleres Metalúrgicos Crucianelli 504
INACTIVO Talleres Metalúrgicos Crucianelli 508
ACTIVO Talleres Metalúrgicos Crucianelli 91
ACTIVO Talleres Metalúrgicos Crucianelli 174
ACTIVO Talleres Metalúrgicos Crucianelli 610
ACTIVO Talleres Metalúrgicos Crucianelli 417
INACTIVO Talleres Metalúrgicos Crucianelli 308
ACTIVO Talleres Metalúrgicos Crucianelli 477
ACTIVO Talleres Metalúrgicos Crucianelli 583
INACTIVO Talleres Metalúrgicos Crucianelli 388
ACTIVO Talleres Metalúrgicos Crucianelli 279
INACTIVO Talleres Metalúrgicos Crucianelli 375
ACTIVO Talleres Metalúrgicos Crucianelli 193
INACTIVO Talleres Metalúrgicos Crucianelli 360
ACTIVO Talleres Metalúrgicos Crucianelli 567
ACTIVO Talleres Metalúrgicos Crucianelli 274
ACTIVO Talleres Metalúrgicos Crucianelli 50
ACTIVO FERTEC S.A. 121
ACTIVO FERTEC S.A. 123
ACTIVO FERTEC S.A. 118
ACTIVO FERTEC S.A. 67
ACTIVO FERTEC S.A. 202
ACTIVO FERTEC S.A. 192
INACTIVO FERTEC S.A. 163
ACTIVO FERTEC S.A. 155
ACTIVO FERTEC S.A. 116
ACTIVO FERTEC S.A. 203
ACTIVO FERTEC S.A. 200
INACTIVO FERTEC S.A. 191
INACTIVO FERTEC S.A. 165
INACTIVO FERTEC S.A. 102
ACTIVO FERTEC S.A. 191
ACTIVO FERTEC S.A. 18
ACTIVO FERTEC S.A. 204
ACTIVO FERTEC S.A. 2
ACTIVO FERTEC S.A. 104
ACTIVO FERTEC S.A. 194
ACTIVO FERTEC S.A. 1
ACTIVO FERTEC S.A. 197
ACTIVO FERTEC S.A. 74
INACTIVO FERTEC S.A. 10
ACTIVO FERTEC S.A. 196
INACTIVO FERTEC S.A. 131
ACTIVO FERTEC S.A. 99
ACTIVO FERTEC S.A. 53
ACTIVO FERTEC S.A. 21
`;

console.log("Script loaded");
